mainnewproject/config/routes.rb
Rails.application.routes.draw do
  resources :students
  get 'usuarios/new'
  #get 'welcome/index'
  resources :usuarios
  root :to => "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

mainnewproject/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

mainnewproject/app/models/student.rb
class Student < ApplicationRecord
end

mainnewproject/app/models/usuario.rb
class Usuario < ApplicationRecord
end

mainnewproject/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

mainnewproject/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :last_name, :document)
    end
end

mainnewproject/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  def new
  end

  # Proceso para crear un usuario
  def create
  	@usuario = Usuario.new usuario_params
  	@usuario.save
    redirect_to usuarios_path
  end

  def index
    #@alluser = Image.all
    @allUsuarios = Usuario.all
  end

  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy

    redirect_to usuarios_path
  end

  def edit 
    @usuario = Usuario.find(params[:id])
  end

  def update
    @usuario = Usuario.find(params[:id])
 
  if @usuario.update(usuario_params)
    redirect_to usuarios_path
  else
    render 'edit'
  end
end
 
private
  private
    def usuario_params
       params.require(:usuario).permit(:nombre, :apellido, :correo)
    end  

end

mainnewproject/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

mainnewproject/app/helpers/application_helper.rb
module ApplicationHelper
end

mainnewproject/app/helpers/students_helper.rb
module StudentsHelper
end

mainnewproject/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

mainnewproject/app/helpers/welcome_helper.rb
module WelcomeHelper
end

mainnewproject/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mainnewproject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

mainnewproject/app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :document %>
    <%= form.number_field :document %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

mainnewproject/app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

mainnewproject/app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Last name</th>
      <th>Document</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.document %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

mainnewproject/app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

mainnewproject/app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Document:</strong>
  <%= @student.document %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

mainnewproject/app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>
 
<%= form_for @usuario, url: usuario_path(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited
      this usuario from being saved:</h2>
    <ul>
    <% @usuario.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </p>
 
  <p>
    <%= f.label :apellido %><br>
    <%= f.text_area :apellido %>
  </p>

  <p>
    <%= f.label :correo %><br>
    <%= f.text_area :correo %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', usuarios_path %>

mainnewproject/app/views/usuarios/index.html.erb
<h1>Lista de usuarios</h1>

<%= link_to 'nuevo usuario', new_usuario_path %>
<br><br><br>

<table>
<tr>
<th>Nombre</th>
<th>Apellido</th>
<th>Correo</th>
<th>Editar</th>
</tr>
<% @allUsuarios.each do |f| %>
<tr>
<td><%= f.nombre %></td>
<td><%= f.apellido %></td>
<td><%= f.correo %></td>
<td><%= link_to 'Editar', edit_usuario_path(f) %></td>
<td><%= link_to 'Destroy', usuario_path(f),
				method: :delete, data: { confirm: 'Estas Seguro?' } %></td>
</tr>
<% end %>
</table>

mainnewproject/app/views/usuarios/new.html.erb
<h1>Creador de usuarios</h1>

<%= form_for :usuario, url: usuarios_path do |f| %>
	<%= f.label :nombre%>
	<%= f.text_field :nombre%>

	<%= f.label :apellido %>
	<%= f.text_field :apellido%>

	<%= f.label :correo%>
	<%= f.text_field :correo%>

	<%= f.submit %>

<% end %>

mainnewproject/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>